name = "StratiGraphics"
uuid = "135379e1-83be-5ae7-9e8e-29dade3dc6c7"
author = "Júlio Hoffimann <julio.hoffimann@gmail.com>"
version = "1.0.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Distributions = "0.25"
ImageFiltering = "0.7"
Random = "1.9"
julia = "1.9"
